default:
  tags:
    - gitlab-org
  image: "ruby:${RUBY_VERSION}"

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

# Or if the project needs to support stable/security branches, use the following instead
workflow:
  rules:
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For `master` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'
    # For stable, and security branches, create a pipeline.
    - if: '$CI_COMMIT_BRANCH =~ /^[\d-]+-stable(-ee)?$/'
    - if: '$CI_COMMIT_BRANCH =~ /^security\//'

rspec:
  cache:
    paths:
      - vendor/ruby
  before_script:
    - ruby -v # Print out ruby version for debugging
    - gem install bundler --no-document # Bundler is not installed with the image
    - bundle config set --local path 'vendor'
    - bundle install -j $(nproc)
  script:
    - bundle exec rake test

  parallel:
    matrix:
      - RUBY_VERSION: ["2.7", "3.0"]
